adb shell
pm uninstall --user 0 com.android.internal.systemui.navbar.twobutton
pm uninstall --user 0 com.android.internal.systemui.navbar.threebutton
pm uninstall --user 0 com.samsung.aasaservice
pm uninstall --user 0 com.sec.hearingadjust
pm uninstall --user 0 com.samsung.android.setting.multisound
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.google.android.ext.services
pm uninstall --user 0 com.google.android.ext.shared
pm uninstall --user 0 com.samsung.android.authfw
pm uninstall --user 0 com.sec.android.app.DataCreate
pm uninstall --user 0 com.sec.android.provider.badge
pm uninstall --user 0 com.samsung.android.sm.devicesecurity
pm uninstall --user 0 com.samsung.android.bbc.bbcagent
pm uninstall --user 0 com.android.theme.color.black
pm uninstall --user 0 com.android.bluetoothmidiservice
pm uninstall --user 0 com.sec.android.app.bluetoothtest
pm uninstall --user 0 com.android.bookmarkprovider
flipboard.boxer.app
pm uninstall --user 0 com.samsung.storyservice
pm uninstall --user 0 com.samsung.android.SettingsReceiver
pm uninstall --user 0 com.samsung.android.sdm.config
pm uninstall --user 0 com.samsung.android.providers.carrier
pm uninstall --user 0 com.samsung.android.app.omcagent
pm uninstall --user 0 com.sec.android.soagent
pm uninstall --user 0 com.wssyncmldm
pm uninstall --user 0 com.android.carrierdefaultapp
pm uninstall --user 0 com.samsung.android.knox.containercore
pm uninstall --user 0 com.samsung.android.knox.containeragent
pm uninstall --user 0 com.samsung.android.lool
pm uninstall --user 0 com.android.dreams.basic
pm uninstall --user 0 com.samsung.android.uds
pm uninstall --user 0 com.samsung.android.mobileservice
pm uninstall --user 0 com.sec.android.app.chromecustomizations
pm uninstall --user 0 com.samsung.android.cidmanager
pm uninstall --user 0 com.android.theme.color.cinnamon
pm uninstall --user 0 com.android.theme.icon_pack.circular.android
pm uninstall --user 0 com.android.theme.icon_pack.circular.systemui
pm uninstall --user 0 com.android.theme.icon_pack.circular.settings
pm uninstall --user 0 com.android.theme.icon_pack.circular.launcher
pm uninstall --user 0 com.android.theme.icon_pack.circular.themepicker
pm uninstall --user 0 com.samsung.cmh
pm uninstall --user 0 com.samsung.android.app.social
pm uninstall --user 0 com.android.cts.ctsshim
pm uninstall --user 0 com.android.cts.priv.ctsshim
pm uninstall --user 0 com.android.localtransport
pm uninstall --user 0 com.android.providers.partnerbookmarks
pm uninstall --user 0 com.google.android.overlay.modules.ext.services
pm uninstall --user 0 com.samsung.android.ipsgeofence
pm uninstall --user 0 com.samsung.android.knox.attestation
pm uninstall --user 0 com.samsung.android.samsungpositioning
pm uninstall --user 0 com.samsung.android.smartfitting
pm uninstall --user 0 com.samsung.android.smartswitchassistant
pm uninstall --user 0 com.samsung.android.wallpaper.res
pm uninstall --user 0 com.samsung.ucs.agent.boot
pm uninstall --user 0 com.sec.android.widgetapp.samsungapps
pm uninstall --user 0 com.sec.bcservice
pm uninstall --user 0 com.sec.enterprise.knox.attestation
pm uninstall --user 0 com.sec.epdg
pm uninstall --user 0 com.sec.ims
pm uninstall --user 0 com.sec.vsimservice
pm uninstall --user 0 com.sec.phone
pm uninstall --user 0 com.samsung.SMT
pm uninstall --user 0 com.samsung.android.container
pm uninstall --user 0 com.samsung.sec.android.application.csc
pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall --user 0 com.sec.android.app.factorykeystring
pm uninstall --user 0 com.sec.factory
pm uninstall --user 0 com.sec.android.diagmonagent
pm uninstall --user 0 com.samsung.android.bixby.service
pm uninstall --user 0 com.samsung.android.themecenter
pm uninstall --user 0 com.samsung.android.dynamiclock
pm uninstall --user 0 com.samsung.android.rubin.app
pm uninstall --user 0 com.sec.mhs.smarttethering
pm uninstall --user 0 com.samsung.crane
pm uninstall --user 0 com.samsung.android.easysetup
pm uninstall --user 0 com.samsung.android.dqagent
pm uninstall --user 0 com.sec.android.app.parser
pm uninstall --user 0 com.samsung.android.dsms
pm uninstall --user 0 com.samsung.android.da.daagent
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.android.dynsystem
pm uninstall --user 0 com.sec.android.easyonehand
pm uninstall --user 0 com.sec.android.emergencymode.service
pm uninstall --user 0 com.sec.android.provider.emergencymode
pm uninstall --user 0 com.samsung.android.emojiupdater
pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin
pm uninstall --user 0 com.sec.epdgtestapp
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.samsung.faceservice
pm uninstall --user 0 com.samsung.android.aircommandmanager
pm uninstall --user 0 com.sec.factory.camera
pm uninstall --user 0 com.android.theme.icon_pack.filled.systemui
pm uninstall --user 0 com.android.theme.icon_pack.filled.themepicker
pm uninstall --user 0 com.android.theme.icon_pack.filled.android
pm uninstall --user 0 com.android.theme.icon_pack.filled.launcher
pm uninstall --user 0 com.android.theme.icon_pack.filled.settings
pm uninstall --user 0 com.samsung.android.app.galaxyfinder
pm uninstall --user 0 com.monotype.android.font.foundation
pm uninstall --user 0 com.sec.android.app.samsungapps
pm uninstall --user 0 com.samsung.android.themestore
pm uninstall --user 0 com.samsung.android.game.gametools
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_narrow_back
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural_wide_back
pm uninstall --user 0 com.android.internal.systemui.navbar.gestural
pm uninstall --user 0 com.samsung.android.mdecservice
pm uninstall --user 0 com.android.settings.intelligence
pm uninstall --user 0 com.android.theme.color.green
pm uninstall --user 0 com.samsung.android.sdk.handwriting
pm uninstall --user 0 com.sec.android.service.health
pm uninstall --user 0 com.sec.android.app.SecSetupWizard
pm uninstall --user 0 com.sec.android.app.hwmoduletest
pm uninstall --user 0 com.sec.imsservice
pm uninstall --user 0 com.samsung.advp.imssettings
pm uninstall --user 0 com.sec.imslogger
pm uninstall --user 0 com.samsung.ipservice
pm uninstall --user 0 com.sec.android.app.magnifier
pm uninstall --user 0 com.samsung.klmsagent
pm uninstall --user 0 com.samsung.android.knox.analytics.uploader
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall --user 0 com.samsung.knox.keychain
pm uninstall --user 0 com.knox.vpn.proxyhandler
pm uninstall --user 0 com.sec.android.emergencylauncher
pm uninstall --user 0 com.google.android.gms.location.history
pm uninstall --user 0 com.samsung.android.app.simplesharing
pm uninstall --user 0 com.samsung.android.bluelightfilter
pm uninstall --user 0 com.sec.app.RilErrorNotifier
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.android.stk2
pm uninstall --user 0 com.samsung.android.mdm
pm uninstall --user 0 com.samsung.android.mdx.quickboard
pm uninstall --user 0 com.samsung.android.net.wifi.wifiguider
pm uninstall --user 0 com.samsung.mlp
pm uninstall --user 0 com.android.mms.service
pm uninstall --user 0 com.samsung.android.allshare.service.mediashare
pm uninstall --user 0 com.samsung.android.networkdiagnostic
pm uninstall --user 0 com.android.theme.font.notoserifsource
pm uninstall --user 0 com.android.theme.color.ocean
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.android.theme.color.orchid
pm uninstall --user 0 com.android.pacprocessor
pm uninstall --user 0 com.sec.android.app.personalization
pm uninstall --user 0 com.android.printspooler
pm uninstall --user 0 com.android.proxyhandler
pm uninstall --user 0 com.android.theme.color.purple
pm uninstall --user 0 com.sec.android.app.fm
pm uninstall --user 0 com.samsung.rcs
pm uninstall --user 0 com.samsung.android.app.reminder
pm uninstall --user 0 com.sec.android.app.ringtoneBR
pm uninstall --user 0 com.android.theme.icon_pack.rounded.systemui
pm uninstall --user 0 com.android.theme.icon_pack.rounded.android
pm uninstall --user 0 com.android.theme.icon_pack.rounded.launcher
pm uninstall --user 0 com.android.theme.icon_pack.rounded.settings
pm uninstall --user 0 com.android.theme.icon.roundedrect
pm uninstall --user 0 com.sec.android.widgetapp.webmanual
pm uninstall --user 0 com.osp.app.signin
pm uninstall --user 0 com.samsung.android.app.smartcapture
pm uninstall --user 0 com.sec.android.app.billing
pm uninstall --user 0 com.samsung.android.scloud
pm uninstall --user 0 com.samsung.android.app.spage
pm uninstall --user 0 com.sec.location.nsflp2
pm uninstall --user 0 com.samsung.android.samsungpass
pm uninstall --user 0 com.sec.spp.push
pm uninstall --user 0 com.samsung.android.sm.policy
pm uninstall --user 0 com.android.se
pm uninstall --user 0 com.samsung.android.securitylogagent
pm uninstall --user 0 com.sec.sve
pm uninstall --user 0 com.sec.android.app.servicemodeapp
pm uninstall --user 0 com.sec.android.RilServiceModeApp
pm uninstall --user 0 com.samsung.android.app.settings.bixby
pm uninstall --user 0 com.sec.android.app.setupwizardlegalprovider
pm uninstall --user 0 com.sec.enterprise.knox.shareddevice.keyguard
pm uninstall --user 0 com.samsung.android.shortcutbackupservice
pm uninstall --user 0 com.android.simappdialog
pm uninstall --user 0 com.skms.android.agent
pm uninstall --user 0 com.samsung.android.location
pm uninstall --user 0 com.samsung.android.smartcallprovider
pm uninstall --user 0 com.sec.android.easyMover.Agent
pm uninstall --user 0 com.samsung.android.smartmirroring
pm uninstall --user 0 com.samsung.android.beaconmanager
pm uninstall --user 0 com.sec.android.app.soundalive
pm uninstall --user 0 com.android.theme.color.space
pm uninstall --user 0 com.sec.android.splitsound
pm uninstall --user 0 com.android.theme.icon.square
pm uninstall --user 0 com.android.theme.icon.squircle
pm uninstall --user 0 com.samsung.android.stickercenter
pm uninstall --user 0 com.samsung.android.svcagent
pm uninstall --user 0 com.samsung.android.samsungpassautofill
pm uninstall --user 0 com.android.theme.icon.teardrop
pm uninstall --user 0 com.trustonic.teeservice
pm uninstall --user 0 com.sec.automation
pm uninstall --user 0 com.android.traceur
pm uninstall --user 0 com.android.managedprovisioning
pm uninstall --user 0 com.sec.android.daemonapp
pm uninstall --user 0 com.samsung.safetyinformation
pm uninstall --user 0 com.android.emergency
pm uninstall --user 0 com.samsung.knox.securefolder
pm uninstall --user 0 com.samsung.android.forest
pm uninstall --user 0 com.samsung.android.fmm
pm uninstall --user 0 com.android.dreams.phototable
pm uninstall --user 0 com.samsung.android.kidsinstaller
pm uninstall --user 0 com.sec.android.preloadinstaller
pm uninstall --user 0 com.sec.android.app.safetyassurance
pm uninstall --user 0 com.sec.android.uibcvirtualsoftkey
pm uninstall --user 0 com.sec.usbsettings
pm uninstall --user 0 com.android.internal.display.cutout.emulation.tall
pm uninstall --user 0 com.android.internal.display.cutout.emulation.double
pm uninstall --user 0 com.android.internal.display.cutout.emulation.corner
pm uninstall --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall --user 0 com.sec.unifiedwfc
pm uninstall --user 0 com.samsung.android.allshare.service.fileshare
pm uninstall --user 0 com.sec.android.app.wlantest
